// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/arena-shell/CurrentMenu.tsx": () => import("../components/mockups/arena-shell/CurrentMenu.tsx"),
  "./components/mockups/arena-shell/CurrentSquad.tsx": () => import("../components/mockups/arena-shell/CurrentSquad.tsx"),
  "./components/mockups/arena-shell/RedesignedMenu.tsx": () => import("../components/mockups/arena-shell/RedesignedMenu.tsx"),
  "./components/mockups/arena-shell/RedesignedSquad.tsx": () => import("../components/mockups/arena-shell/RedesignedSquad.tsx")
};
